eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: api-gateway

server:
  port: API_GATEWAY_PORT

microservice:
  auth_service: AUTH_ROUTE
  user_service: USER_ROUTE
  news_service: NEWS_ROUTE
  notification_service: NOTIFICATION_ROUTE
  search_service: SEARCH_ROUTE
  subscription_service: SUBSCRIPTION_ROUTE