server:
  port: CONFIG_PORT # Default port for Config Server

spring:
  application:
      name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: GIT_URI_CONFIG # Git repository URL
          default-label: BRANCH_CONFIG
        native:
          search-locations: SEARCH_LOCATIONS #classpath:/config-repo
  security:
    user:
      name: CONFIG_USER
      password: CONFIG_PASSWORD